// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: followingfeed.proto

package followingfeed

import (
	"context"

	"posta/application/followingfeed/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFollowingItem     = pb.GetFollowingItem
	GetFollowingRequest  = pb.GetFollowingRequest
	GetFollowingResponse = pb.GetFollowingResponse

	FollowingFeed interface {
		GetFollowingFeed(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error)
	}

	defaultFollowingFeed struct {
		cli zrpc.Client
	}
)

func NewFollowingFeed(cli zrpc.Client) FollowingFeed {
	return &defaultFollowingFeed{
		cli: cli,
	}
}

func (m *defaultFollowingFeed) GetFollowingFeed(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error) {
	client := pb.NewFollowingFeedClient(m.cli.Conn())
	return client.GetFollowingFeed(ctx, in, opts...)
}
