// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: followingfeed.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CursorSmallUp int64                  `protobuf:"varint,2,opt,name=cursorSmallUp,proto3" json:"cursorSmallUp,omitempty"` // 存储的是时间，用于游标分页
	InboxId       int64                  `protobuf:"varint,3,opt,name=inboxId,proto3" json:"inboxId,omitempty"`             // 用于当cursor重复时即进一步区分
	CursorBigUp   int64                  `protobuf:"varint,4,opt,name=cursorBigUp,proto3" json:"cursorBigUp,omitempty"`
	ArticleId     int64                  `protobuf:"varint,5,opt,name=articleId,proto3" json:"articleId,omitempty"`
	PageSize      int64                  `protobuf:"varint,6,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_followingfeed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_followingfeed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_followingfeed_proto_rawDescGZIP(), []int{0}
}

func (x *GetFollowingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowingRequest) GetCursorSmallUp() int64 {
	if x != nil {
		return x.CursorSmallUp
	}
	return 0
}

func (x *GetFollowingRequest) GetInboxId() int64 {
	if x != nil {
		return x.InboxId
	}
	return 0
}

func (x *GetFollowingRequest) GetCursorBigUp() int64 {
	if x != nil {
		return x.CursorBigUp
	}
	return 0
}

func (x *GetFollowingRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *GetFollowingRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFollowingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	CommentCount  int64                  `protobuf:"varint,6,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	PublishTime   int64                  `protobuf:"varint,8,opt,name=publishTime,proto3" json:"publishTime,omitempty"`
	AuthorId      int64                  `protobuf:"varint,9,opt,name=authorId,proto3" json:"authorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingItem) Reset() {
	*x = GetFollowingItem{}
	mi := &file_followingfeed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingItem) ProtoMessage() {}

func (x *GetFollowingItem) ProtoReflect() protoreflect.Message {
	mi := &file_followingfeed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingItem.ProtoReflect.Descriptor instead.
func (*GetFollowingItem) Descriptor() ([]byte, []int) {
	return file_followingfeed_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowingItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetFollowingItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetFollowingItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetFollowingItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetFollowingItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *GetFollowingItem) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *GetFollowingItem) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *GetFollowingItem) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

func (x *GetFollowingItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type GetFollowingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowingItems []*GetFollowingItem    `protobuf:"bytes,1,rep,name=followingItems,proto3" json:"followingItems,omitempty"`
	IsEnd          bool                   `protobuf:"varint,2,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	CursorSmallUp  int64                  `protobuf:"varint,3,opt,name=cursorSmallUp,proto3" json:"cursorSmallUp,omitempty"`
	InboxId        int64                  `protobuf:"varint,4,opt,name=inboxId,proto3" json:"inboxId,omitempty"`
	CursorBigUp    int64                  `protobuf:"varint,5,opt,name=cursorBigUp,proto3" json:"cursorBigUp,omitempty"`
	ArticleId      int64                  `protobuf:"varint,6,opt,name=articleId,proto3" json:"articleId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_followingfeed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_followingfeed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_followingfeed_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowingResponse) GetFollowingItems() []*GetFollowingItem {
	if x != nil {
		return x.FollowingItems
	}
	return nil
}

func (x *GetFollowingResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *GetFollowingResponse) GetCursorSmallUp() int64 {
	if x != nil {
		return x.CursorSmallUp
	}
	return 0
}

func (x *GetFollowingResponse) GetInboxId() int64 {
	if x != nil {
		return x.InboxId
	}
	return 0
}

func (x *GetFollowingResponse) GetCursorBigUp() int64 {
	if x != nil {
		return x.CursorBigUp
	}
	return 0
}

func (x *GetFollowingResponse) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

var File_followingfeed_proto protoreflect.FileDescriptor

const file_followingfeed_proto_rawDesc = "" +
	"\n" +
	"\x13followingfeed.proto\x12\x02pb\"\xc9\x01\n" +
	"\x13GetFollowingRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12$\n" +
	"\rcursorSmallUp\x18\x02 \x01(\x03R\rcursorSmallUp\x12\x18\n" +
	"\ainboxId\x18\x03 \x01(\x03R\ainboxId\x12 \n" +
	"\vcursorBigUp\x18\x04 \x01(\x03R\vcursorBigUp\x12\x1c\n" +
	"\tarticleId\x18\x05 \x01(\x03R\tarticleId\x12\x1a\n" +
	"\bpageSize\x18\x06 \x01(\x03R\bpageSize\"\x8a\x02\n" +
	"\x10GetFollowingItem\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\"\n" +
	"\fcommentCount\x18\x06 \x01(\x03R\fcommentCount\x12\x1c\n" +
	"\tlikeCount\x18\a \x01(\x03R\tlikeCount\x12 \n" +
	"\vpublishTime\x18\b \x01(\x03R\vpublishTime\x12\x1a\n" +
	"\bauthorId\x18\t \x01(\x03R\bauthorId\"\xea\x01\n" +
	"\x14GetFollowingResponse\x12<\n" +
	"\x0efollowingItems\x18\x01 \x03(\v2\x14.pb.GetFollowingItemR\x0efollowingItems\x12\x14\n" +
	"\x05isEnd\x18\x02 \x01(\bR\x05isEnd\x12$\n" +
	"\rcursorSmallUp\x18\x03 \x01(\x03R\rcursorSmallUp\x12\x18\n" +
	"\ainboxId\x18\x04 \x01(\x03R\ainboxId\x12 \n" +
	"\vcursorBigUp\x18\x05 \x01(\x03R\vcursorBigUp\x12\x1c\n" +
	"\tarticleId\x18\x06 \x01(\x03R\tarticleId2V\n" +
	"\rFollowingFeed\x12E\n" +
	"\x10GetFollowingFeed\x12\x17.pb.GetFollowingRequest\x1a\x18.pb.GetFollowingResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_followingfeed_proto_rawDescOnce sync.Once
	file_followingfeed_proto_rawDescData []byte
)

func file_followingfeed_proto_rawDescGZIP() []byte {
	file_followingfeed_proto_rawDescOnce.Do(func() {
		file_followingfeed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_followingfeed_proto_rawDesc), len(file_followingfeed_proto_rawDesc)))
	})
	return file_followingfeed_proto_rawDescData
}

var file_followingfeed_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_followingfeed_proto_goTypes = []any{
	(*GetFollowingRequest)(nil),  // 0: pb.GetFollowingRequest
	(*GetFollowingItem)(nil),     // 1: pb.GetFollowingItem
	(*GetFollowingResponse)(nil), // 2: pb.GetFollowingResponse
}
var file_followingfeed_proto_depIdxs = []int32{
	1, // 0: pb.GetFollowingResponse.followingItems:type_name -> pb.GetFollowingItem
	0, // 1: pb.FollowingFeed.GetFollowingFeed:input_type -> pb.GetFollowingRequest
	2, // 2: pb.FollowingFeed.GetFollowingFeed:output_type -> pb.GetFollowingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_followingfeed_proto_init() }
func file_followingfeed_proto_init() {
	if File_followingfeed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_followingfeed_proto_rawDesc), len(file_followingfeed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_followingfeed_proto_goTypes,
		DependencyIndexes: file_followingfeed_proto_depIdxs,
		MessageInfos:      file_followingfeed_proto_msgTypes,
	}.Build()
	File_followingfeed_proto = out.File
	file_followingfeed_proto_goTypes = nil
	file_followingfeed_proto_depIdxs = nil
}
