// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: followingfeed.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FollowingFeed_GetFollowingFeed_FullMethodName = "/pb.FollowingFeed/GetFollowingFeed"
)

// FollowingFeedClient is the client API for FollowingFeed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FollowingFeedClient interface {
	GetFollowingFeed(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error)
}

type followingFeedClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowingFeedClient(cc grpc.ClientConnInterface) FollowingFeedClient {
	return &followingFeedClient{cc}
}

func (c *followingFeedClient) GetFollowingFeed(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowingResponse)
	err := c.cc.Invoke(ctx, FollowingFeed_GetFollowingFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowingFeedServer is the server API for FollowingFeed service.
// All implementations must embed UnimplementedFollowingFeedServer
// for forward compatibility.
type FollowingFeedServer interface {
	GetFollowingFeed(context.Context, *GetFollowingRequest) (*GetFollowingResponse, error)
	mustEmbedUnimplementedFollowingFeedServer()
}

// UnimplementedFollowingFeedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowingFeedServer struct{}

func (UnimplementedFollowingFeedServer) GetFollowingFeed(context.Context, *GetFollowingRequest) (*GetFollowingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowingFeed not implemented")
}
func (UnimplementedFollowingFeedServer) mustEmbedUnimplementedFollowingFeedServer() {}
func (UnimplementedFollowingFeedServer) testEmbeddedByValue()                       {}

// UnsafeFollowingFeedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowingFeedServer will
// result in compilation errors.
type UnsafeFollowingFeedServer interface {
	mustEmbedUnimplementedFollowingFeedServer()
}

func RegisterFollowingFeedServer(s grpc.ServiceRegistrar, srv FollowingFeedServer) {
	// If the following call pancis, it indicates UnimplementedFollowingFeedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowingFeed_ServiceDesc, srv)
}

func _FollowingFeed_GetFollowingFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowingFeedServer).GetFollowingFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowingFeed_GetFollowingFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowingFeedServer).GetFollowingFeed(ctx, req.(*GetFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowingFeed_ServiceDesc is the grpc.ServiceDesc for FollowingFeed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowingFeed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FollowingFeed",
	HandlerType: (*FollowingFeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFollowingFeed",
			Handler:    _FollowingFeed_GetFollowingFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "followingfeed.proto",
}
