apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: posta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2.4  # ← 使用具体版本号，不要用latest，不然k8s还是要尝试去拉取最新的而不是使用本地的
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: posta
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
