// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: like.proto

package server

import (
	"context"

	"posta/application/like/rpc/internal/logic"
	"posta/application/like/rpc/internal/svc"
	"posta/application/like/rpc/pb"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

// 用户对某个对象点赞或取消点赞
func (s *LikeServer) LikeAction(ctx context.Context, in *pb.LikeActionRequest) (*pb.LikeActionResponse, error) {
	l := logic.NewLikeActionLogic(ctx, s.svcCtx)
	return l.LikeAction(in)
}

// 查询用户是否点赞（单个）
func (s *LikeServer) IsLiked(ctx context.Context, in *pb.IsLikedRequest) (*pb.IsLikedResponse, error) {
	l := logic.NewIsLikedLogic(ctx, s.svcCtx)
	return l.IsLiked(in)
}

// 查询点赞数（单个）
func (s *LikeServer) LikeCount(ctx context.Context, in *pb.LikeCountRequest) (*pb.LikeCountResponse, error) {
	l := logic.NewLikeCountLogic(ctx, s.svcCtx)
	return l.LikeCount(in)
}
