// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: followingfeed.proto

package server

import (
	"context"

	"posta/application/followingfeed/rpc/internal/logic"
	"posta/application/followingfeed/rpc/internal/svc"
	"posta/application/followingfeed/rpc/pb"
)

type FollowingFeedServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFollowingFeedServer
}

func NewFollowingFeedServer(svcCtx *svc.ServiceContext) *FollowingFeedServer {
	return &FollowingFeedServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowingFeedServer) GetFollowingFeed(ctx context.Context, in *pb.GetFollowingRequest) (*pb.GetFollowingResponse, error) {
	l := logic.NewGetFollowingFeedLogic(ctx, s.svcCtx)
	return l.GetFollowingFeed(in)
}
