// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: like.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 点赞或取消点赞请求
type LikeActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         int64                  `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`    // 业务类型，这里的话可以是 "article"或"reply"
	ObjId         int64                  `protobuf:"varint,2,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`    // 点赞目标ID
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Action        int32                  `protobuf:"varint,4,opt,name=action,proto3" json:"action,omitempty"`               // 操作类型：0点赞，1取消点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeActionRequest) Reset() {
	*x = LikeActionRequest{}
	mi := &file_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeActionRequest) ProtoMessage() {}

func (x *LikeActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeActionRequest.ProtoReflect.Descriptor instead.
func (*LikeActionRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{0}
}

func (x *LikeActionRequest) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *LikeActionRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *LikeActionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeActionRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// 点赞响应
type LikeActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 返回操作是否成功
	Liked         bool                   `protobuf:"varint,2,opt,name=liked,proto3" json:"liked,omitempty"`     // 当前操作后是否处于点赞状态（true=已点赞，false=未点赞）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeActionResponse) Reset() {
	*x = LikeActionResponse{}
	mi := &file_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeActionResponse) ProtoMessage() {}

func (x *LikeActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeActionResponse.ProtoReflect.Descriptor instead.
func (*LikeActionResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{1}
}

func (x *LikeActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LikeActionResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type IsLikedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         int64                  `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	ObjId         int64                  `protobuf:"varint,2,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLikedRequest) Reset() {
	*x = IsLikedRequest{}
	mi := &file_like_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLikedRequest) ProtoMessage() {}

func (x *IsLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLikedRequest.ProtoReflect.Descriptor instead.
func (*IsLikedRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{2}
}

func (x *IsLikedRequest) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *IsLikedRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

func (x *IsLikedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsLikedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLikedResponse) Reset() {
	*x = IsLikedResponse{}
	mi := &file_like_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLikedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLikedResponse) ProtoMessage() {}

func (x *IsLikedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLikedResponse.ProtoReflect.Descriptor instead.
func (*IsLikedResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{3}
}

func (x *IsLikedResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type LikeCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         int64                  `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	ObjId         int64                  `protobuf:"varint,2,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCountRequest) Reset() {
	*x = LikeCountRequest{}
	mi := &file_like_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCountRequest) ProtoMessage() {}

func (x *LikeCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCountRequest.ProtoReflect.Descriptor instead.
func (*LikeCountRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{4}
}

func (x *LikeCountRequest) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *LikeCountRequest) GetObjId() int64 {
	if x != nil {
		return x.ObjId
	}
	return 0
}

type LikeCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCountResponse) Reset() {
	*x = LikeCountResponse{}
	mi := &file_like_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCountResponse) ProtoMessage() {}

func (x *LikeCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCountResponse.ProtoReflect.Descriptor instead.
func (*LikeCountResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{5}
}

func (x *LikeCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_like_proto protoreflect.FileDescriptor

const file_like_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"like.proto\x12\x02pb\"r\n" +
	"\x11LikeActionRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\x03R\x05bizId\x12\x15\n" +
	"\x06obj_id\x18\x02 \x01(\x03R\x05objId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\x05R\x06action\"D\n" +
	"\x12LikeActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05liked\x18\x02 \x01(\bR\x05liked\"W\n" +
	"\x0eIsLikedRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\x03R\x05bizId\x12\x15\n" +
	"\x06obj_id\x18\x02 \x01(\x03R\x05objId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"'\n" +
	"\x0fIsLikedResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\"@\n" +
	"\x10LikeCountRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\x03R\x05bizId\x12\x15\n" +
	"\x06obj_id\x18\x02 \x01(\x03R\x05objId\")\n" +
	"\x11LikeCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\xb1\x01\n" +
	"\x04Like\x12;\n" +
	"\n" +
	"LikeAction\x12\x15.pb.LikeActionRequest\x1a\x16.pb.LikeActionResponse\x122\n" +
	"\aIsLiked\x12\x12.pb.IsLikedRequest\x1a\x13.pb.IsLikedResponse\x128\n" +
	"\tLikeCount\x12\x14.pb.LikeCountRequest\x1a\x15.pb.LikeCountResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_like_proto_rawDescOnce sync.Once
	file_like_proto_rawDescData []byte
)

func file_like_proto_rawDescGZIP() []byte {
	file_like_proto_rawDescOnce.Do(func() {
		file_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_like_proto_rawDesc), len(file_like_proto_rawDesc)))
	})
	return file_like_proto_rawDescData
}

var file_like_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_like_proto_goTypes = []any{
	(*LikeActionRequest)(nil),  // 0: pb.LikeActionRequest
	(*LikeActionResponse)(nil), // 1: pb.LikeActionResponse
	(*IsLikedRequest)(nil),     // 2: pb.IsLikedRequest
	(*IsLikedResponse)(nil),    // 3: pb.IsLikedResponse
	(*LikeCountRequest)(nil),   // 4: pb.LikeCountRequest
	(*LikeCountResponse)(nil),  // 5: pb.LikeCountResponse
}
var file_like_proto_depIdxs = []int32{
	0, // 0: pb.Like.LikeAction:input_type -> pb.LikeActionRequest
	2, // 1: pb.Like.IsLiked:input_type -> pb.IsLikedRequest
	4, // 2: pb.Like.LikeCount:input_type -> pb.LikeCountRequest
	1, // 3: pb.Like.LikeAction:output_type -> pb.LikeActionResponse
	3, // 4: pb.Like.IsLiked:output_type -> pb.IsLikedResponse
	5, // 5: pb.Like.LikeCount:output_type -> pb.LikeCountResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_like_proto_init() }
func file_like_proto_init() {
	if File_like_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_like_proto_rawDesc), len(file_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_like_proto_goTypes,
		DependencyIndexes: file_like_proto_depIdxs,
		MessageInfos:      file_like_proto_msgTypes,
	}.Build()
	File_like_proto = out.File
	file_like_proto_goTypes = nil
	file_like_proto_depIdxs = nil
}
