// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type LoginRequest struct {
	Mobile           string `json:"Mobile"`
	VerificationCode string `json:"verificationCode"`
}

type LoginResponse struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type RegisterRequest struct {
	Name             string `json:"name"`
	Mobile           string `json:"mobile"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
}

type RegisterResponse struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type VerificationRequest struct {
	Mobile string `json:"mobile"`
}

type VerificationResponse struct {
}
