// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

import "posta/pkg/jwt"

type LoginRequest struct {
	Mobile           string `json:"Mobile"`
	VerificationCode string `json:"verificationCode"`
}

type LoginResponse struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type RegisterRequest struct {
	Name             string `json:"name"`
	Mobile           string `json:"mobile"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
}

type RegisterResponse struct {
	UserId int64 `json:"userId"`
	// 注意：这里的 Token 是 jwt.Token 类型，而不是 string 类型。这里是手动改的
	Token jwt.Token `json:"token"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type VerificationRequest struct {
	Mobile string `json:"mobile"`
}

type VerificationResponse struct {
}
