// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.4

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followCountFieldNames          = builder.RawFieldNames(&FollowCount{})
	followCountRows                = strings.Join(followCountFieldNames, ",")
	followCountRowsExpectAutoSet   = strings.Join(stringx.Remove(followCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followCountRowsWithPlaceHolder = strings.Join(stringx.Remove(followCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	followCountModel interface {
		Insert(ctx context.Context, data *FollowCount) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*FollowCount, error)
		FindOneByUserId(ctx context.Context, userId int64) (*FollowCount, error)
		Update(ctx context.Context, data *FollowCount) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFollowCountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FollowCount struct {
		Id          int64     `db:"id"`           // 主键ID
		UserId      int64     `db:"user_id"`      // 用户ID
		FollowCount int64     `db:"follow_count"` // 关注数
		FansCount   uint64    `db:"fans_count"`   // 粉丝数
		CreateTime  time.Time `db:"create_time"`  // 创建时间
		UpdateTime  time.Time `db:"update_time"`  // 最后修改时间
	}
)

func newFollowCountModel(conn sqlx.SqlConn) *defaultFollowCountModel {
	return &defaultFollowCountModel{
		conn:  conn,
		table: "`follow_count`",
	}
}

func (m *defaultFollowCountModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFollowCountModel) FindOne(ctx context.Context, id int64) (*FollowCount, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followCountRows, m.table)
	var resp FollowCount
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowCountModel) FindOneByUserId(ctx context.Context, userId int64) (*FollowCount, error) {
	var resp FollowCount
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", followCountRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowCountModel) Insert(ctx context.Context, data *FollowCount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, followCountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FollowCount, data.FansCount)
	return ret, err
}

func (m *defaultFollowCountModel) Update(ctx context.Context, newData *FollowCount) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, followCountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.FollowCount, newData.FansCount, newData.Id)
	return err
}

func (m *defaultFollowCountModel) tableName() string {
	return m.table
}
